import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./layout/header/page";
import "bootstrap/dist/css/bootstrap.min.css";
import Footer from "./footer/page";
import "@fontsource/poppins"; // Defaults to weight 400
import { Poppins } from "next/font/google";
import { Toaster } from "react-hot-toast";

// Import and configure the font
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"], // Optional weights
  variable: "--font-poppins", // Optional: use as CSS variable
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function FrontLayout({ children }) {
  return (
    <html lang="en" className={poppins.className}>
      {/* <link
        href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;600&display=swap"
        rel="stylesheet"
      /> */}
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-light`}
      >
        <Header />
        <Toaster
          position="top-right"
          toastOptions={{
            // Global styles
            style: {
              background: "#333",
              color: "#fff",
            },
            success: {
              style: {
                background: "green",
              },
            },
            error: {
              style: {
                background: "red",
              },
            },
          }}
        />
        {children}
      </body>
    </html>
  );
}
